# Generated by Django 3.2.12 on 2022-11-13 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='assignments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_assignment', models.TextField()),
                ('file_assignment', models.FileField(upload_to='')),
                ('deadline_assignment', models.DateTimeField()),
                ('message_assignment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='exams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_exam', models.TextField()),
                ('file_exam', models.FileField(upload_to='')),
                ('deadline_exam', models.DateTimeField()),
                ('message_exam', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='make_announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='publish_ppt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_publish', models.FileField(upload_to='')),
                ('message_publish', models.TextField()),
            ],
        ),
    ]
