# Generated by Django 3.2.12 on 2022-11-14 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='file_assignment',
            field=models.TextField(),
        ),
    ]
