# Generated by Django 3.2.12 on 2022-11-14 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0003_assignments_posted_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='exams',
            name='posted_on',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
